version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  node16:
    docker:
      - image: "cypress/base:16.13.0"
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: yarn install --frozen-lockfile
          build: "npm run build"
      - cypress/run:
          executor: node16
          browser: chrome
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: "all tests"
          start: "npm start"
