version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@5.0.2
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: 7yarn install --frozen-lockfile
          build: "npm run build" # run a custom app build step
      - cypress/run:
          executor: cypress/base-16
          requires:
            - cypress/install
          record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          group: "all tests" # name this group "all tests" on the dashboard
          start: "npm start" # start server before running tests
