version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-cypress:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Deps
          command: apt-get update -y && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb curl
      - node/install:
          node-version: '16.15.0'
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Update Packages
          command: yarn upgrade
      - run:
          name: Build
          command: yarn build
      - run:
          name: Cypress
          command: yarn e2e:headless

workflows:
  newfolio:
    jobs:
      - test-cypress
