version: 2.1

orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@4.1
  macos: circleci/macos@2.2.0


jobs:
  build-linux:
    docker:
      - image: cimg/node:18.1.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Build
          command: pnpm build
  build-windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.1.0'
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Build
          command: pnpm build
  build-macos:
    macos:
       xcode: 11.7
    steps:
      - checkout
      - node/install:
          node-version: '18.1.0'
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Build
          command: pnpm build

workflows:
  newfolio:
    jobs:
      - build-linux
      - build-windows
      - build-macos
